### ISSUE TITLE
Make LIBMADAM crashes 

### ISSUE THREAD

**Issue by kumasura** [hpc4cmb/libmadam#11]
I am trying to make the executables for libmadam. My configuration has successfully completed. however, i am unable to make it. It crashes with following errors:

kumasura@cori07:~/libmadam> make
make  all-recursive
make[1]: Entering directory '/global/u2/k/kumasura/libmadam'
Making all in src
make[2]: Entering directory '/global/u2/k/kumasura/libmadam/src'
/bin/sh ../libtool  --tag=CC   --mode=link mpicc  -O3 -fopenmp  -fopenmp -o test_libmadam test_libmadam.o libmadam.la  -L/usr/common/software/fftw/3.3.4/hsw/intel//lib -lfftw3   -lm -L/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_scalapack_ilp64.a -Wl,--start-group /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_cdft_core.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_gf_ilp64.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_gnu_thread.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_blacs_openmpi_ilp64.a /usr/common/software/cfitsio/3.370-reentrant/hsw/intel/lib/libcfitsio.a /usr/common/software/fftw/3.3.4/hsw/intel/lib/libfftw3.a -Wl,--end-group -lgomp -lpthread -lm -ldl
libtool: link: mpicc -O3 -fopenmp -fopenmp -o .libs/test_libmadam test_libmadam.o -Wl,--start-group -Wl,--end-group  ./.libs/libmadam.so -L/usr/common/software/fftw/3.3.4/hsw/intel//lib -L/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_scalapack_ilp64.a -liomp5 /usr/common/software/fftw/3.3.4/hsw/intel/lib/libfftw3.so /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_cdft_core.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_gf_ilp64.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_gnu_thread.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_blacs_openmpi_ilp64.a /usr/common/software/cfitsio/3.370-reentrant/hsw/intel/lib/libcfitsio.a /usr/common/software/fftw/3.3.4/hsw/intel/lib/libfftw3.a /opt/gcc/7.3.0/snos/lib/../lib64/libgomp.so -lpthread -lm -ldl -fopenmp -Wl,-rpath -Wl,/usr/common/software/fftw/3.3.4/hsw/intel/lib -Wl,-rpath -Wl,/opt/gcc/7.3.0/snos/lib/../lib64
/usr/bin/ld: /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a(dsbrdb.o): in function `mkl_lapack_dsbrdb':
dsbrdb_gen.f:(.text+0xdf): undefined reference to `mkl_lapack_dsbrdbn'
/usr/bin/ld: dsbrdb_gen.f:(.text+0x1de7): undefined reference to `mkl_lapack_dlaeh2'
/usr/bin/ld: dsbrdb_gen.f:(.text+0x2f57): undefined reference to `mkl_lapack_dlaeh2'
/usr/bin/ld: /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a(_avx_d__trmm_rut.o): in function `mkl_blas_avx_dtrmm_rut':
_trmm_rut.f:(.text+0x818f): undefined reference to `mkl_blas_daxpy'
/usr/bin/ld: /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a(_avx_d__trmm_run.o): in function `mkl_blas_avx_dtrmm_run':
_trmm_run.f:(.text+0x8140): undefined reference to `mkl_blas_daxpy'
/usr/bin/ld: /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a(_avx_d__trmm_rlt.o): in function `mkl_blas_avx_dtrmm_rlt':
_trmm_rlt.f:(.text+0x84e1): undefined reference to `mkl_blas_daxpy'
/usr/bin/ld: /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a(_avx_d__trmm_rln.o): in function `mkl_blas_avx_dtrmm_rln':
_trmm_rln.f:(.text+0x81c2): undefined reference to `mkl_blas_daxpy'
/usr/bin/ld: /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a(_mc3_d__trmm_rut.o): in function `mkl_blas_mc3_dtrmm_rut':
_trmm_rut.f:(.text+0x7bfb): undefined reference to `mkl_blas_daxpy'
/usr/bin/ld: /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a(_mc3_d__trmm_run.o):_trmm_run.f:(.text+0x7961): more undefined references to `mkl_blas_daxpy' follow
/usr/bin/ld: link errors found, deleting executable `.libs/test_libmadam'
Makefile:684: recipe for target 'test_libmadam' failed
make[2]: *** [test_libmadam] Error 1
make[2]: Leaving directory '/global/u2/k/kumasura/libmadam/src'
Makefile:414: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/global/u2/k/kumasura/libmadam'
Makefile:345: recipe for target 'all' failed
make: *** [all] Error 2

The current loaded module in the environment are:

kumasura@cori07:~/libmadam> module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.6                                 13) ugni/6.0.14.0-6.0.7.1_3.13__gea11d3d.ari
  2) nsg/1.2.0                                        14) pmi/5.0.14
  3) craype-haswell                                   15) dmapp/7.1.1-6.0.7.1_5.45__g5a674e0.ari
  4) craype-network-aries                             16) gni-headers/5.0.12.0-6.0.7.1_3.11__g3b1768f.ari
  5) craype/2.5.15                                    17) xpmem/2.2.15-6.0.7.1_5.11__g7549d06.ari
  6) cray-mpich/7.7.3                                 18) job/2.2.3-6.0.7.1_5.43__g6c4e934.ari
  7) openmpi/3.1.3                                    19) dvs/2.7_2.2.118-6.0.7.1_10.1__g58b37a2
  8) gcc/7.3.0                                        20) alps/6.6.43-6.0.7.1_5.45__ga796da32.ari
  9) altd/2.0                                         21) rca/2.2.18-6.0.7.1_5.47__g2aa4f39.ari
 10) darshan/3.1.4                                    22) atp/2.1.3
 11) cray-libsci/18.07.1                              23) PrgEnv-gnu/6.0.4
 12) udreg/2.3.2-6.0.7.1_5.13__g5196236.ari           24) intel/18.0.1.163

Please help me resolve the problem?

**Comment by keskitalo** [comment]
This seems to be specific to NERSC environment on Cori rather than an issue with `libMadam`. The linker is not finding MKL symbols. We do compile and run `libMadam` at NERSC using a variety of software stacks. Before I can give advice I'll need some details:

1.  Do you have `cfitsio` compiled yourself?
2. Do you intend to use MKL or FFTW for the FFT:s? Where are these libraries located?
3. What was the precise command line you used to `configure` before calling `make`?

**Comment by kumasura** [comment]
Dear keskitalo,

1. The **cfitsio** was installed as dependency during installation of CosmoMC. 
2.  I have exported the location of MKL libraries in the LIBS parameter as:
**LIBS = "-L/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_scalapack_ilp64.a -Wl,--start-group /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_cdft_core.a /usr/common/software/cfitsio/3.370-reentrant/hsw/intel/lib/libcfitsio.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_intel_ilp64.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_intel_thread.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_core.a /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_blacs_openmpi_ilp64.a /usr/common/software/fftw/3.3.4/hsw/intel/lib/libfftw3.a -Wl,--end-group -liomp5 -lpthread -lm -ldl"**

3. The configure command used was:
**./configure --with-fftw=/usr/common/software/fftw/3.3.4/hsw/intel/**

**Comment by keskitalo** [comment]
You really should not need to declare every MKL library like that. These steps worked for me from a clean Cori login shell:
```
module load cfitsio
./configure --with-cfitsio=${CFITSIO_DIR} --with-fftw=/usr/common/software/fftw/3.3.8/skl/gcc/7.3.0
CRAYPE_LINK_TYPE=dynamic make
```

Notice that I didn't load the `fftw` module to set `FFTW_DIR`. It seems to have a bug that breaks the Cray compiler wrappers. I filed a ticket with NERSC.

You can test the library on a KNL compute node:
```
salloc -t 04:00:00 -C knl --qos interactive
...
CRAYPE_LINK_TYPE=dynamic make check
exit
```

**Comment by keskitalo** [comment]
This will also work:
```
module load cray-fftw
./configure --with-cfitsio=${CFITSIO_DIR} --with-fftw=${FFTW_DIR/lib\//}
CRAYPE_LINK_TYPE=dynamic make
```

**Comment by kumasura** [comment]
Even from the fresh cori terminal with following modules, i am getting the same error as:

kumasura@cori11:~/libmadam> CRAYPE_LINK_TYPE=dynamic make      
make  all-recursive
make[1]: Entering directory '/global/u2/k/kumasura/libmadam'
Making all in src
make[2]: Entering directory '/global/u2/k/kumasura/libmadam/src'
cc -DHAVE_CONFIG_H -I. -I..  -DMPIWRITECOVMAT   -O3 -fopenmp -MT test_libmadam.o -MD -MP -MF .deps/test_libmadam.Tpo -c -o test_libmadam.o test_libmadam.c
mv -f .deps/test_libmadam.Tpo .deps/test_libmadam.Po
/bin/sh ../libtool  --tag=CC   --mode=link cc  -O3 -fopenmp  -fopenmp -o test_libmadam test_libmadam.o libmadam.la -L/usr/common/software/cfitsio/3.370-reentrant/hsw/intel/lib -lcfitsio -L/usr/common/software/fftw/3.3.8/skl/gcc/7.3.0/lib -lfftw3   -lm 
libtool: link: cc -O3 -fopenmp -fopenmp -o .libs/test_libmadam test_libmadam.o  ./.libs/libmadam.so -L/usr/common/software/fftw/3.3.4/hsw/intel//lib -L/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64/libmkl_scalapack_ilp64.a /usr/common/software/fftw/3.3.4/hsw/intel/lib/libfftw3.so -liomp5 -lpthread -ldl -lirc -L/usr/common/software/cfitsio/3.370-reentrant/hsw/intel/lib -lcfitsio -L/usr/common/software/fftw/3.3.8/skl/gcc/7.3.0/lib /global/common/cori/software/fftw/3.3.8/skl/gcc/7.3.0/lib/libfftw3.so -lm -fopenmp -Wl,-rpath -Wl,/usr/common/software/fftw/3.3.4/hsw/intel/lib -Wl,-rpath -Wl,/global/common/cori/software/fftw/3.3.8/skl/gcc/7.3.0/lib
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_dlacpy'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_trans_mkl_somatcopy2_par'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_dsytrd'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_blas_dtrmm'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_ao_dpotrf_hao'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_trans_mkl_domatcopy2_par'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_trans_mkl_simatcopy_square_t_par'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_blas_dtrmv'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_blas_dsymm'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_dgeqlf_pf'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_trans_mkl_dimatcopy_square_t_par'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_trans_mkl_zomatcopy2_par'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_trans_mkl_comatcopy2_par'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_blas_dsyr2k'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_dgeqrf_pf'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_dlasr3'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_blas_dscal'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_dlansy'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_trans_mkl_zimatcopy_square_t_par'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_blas_ddot'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_dorgql'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_trans_mkl_cimatcopy_square_t_par'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_blas_dtrsv'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_dlaset'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_dsbrdbm'
/usr/bin/ld: ./.libs/libmadam.so: undefined reference to `mkl_lapack_dorgqr'
/usr/bin/ld: link errors found, deleting executable `.libs/test_libmadam'
Makefile:684: recipe for target 'test_libmadam' failed
make[2]: *** [test_libmadam] Error 1
make[2]: Leaving directory '/global/u2/k/kumasura/libmadam/src'
Makefile:414: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/global/u2/k/kumasura/libmadam'
Makefile:345: recipe for target 'all' failed
make: *** [all] Error 2

Is there anything i am missing in the environment like which PrgEnv should it be compiled.

**Comment by kumasura** [comment]
Modules:

Currently Loaded Modulefiles:
  1) modules/3.2.10.6
  2) nsg/1.2.0
  3) intel/18.0.1.163
  4) craype-network-aries
  5) craype/2.5.15
  6) cray-libsci/18.07.1
  7) udreg/2.3.2-6.0.7.1_5.13__g5196236.ari
  8) ugni/6.0.14.0-6.0.7.1_3.13__gea11d3d.ari
  9) pmi/5.0.14
 10) dmapp/7.1.1-6.0.7.1_5.45__g5a674e0.ari
 11) gni-headers/5.0.12.0-6.0.7.1_3.11__g3b1768f.ari
 12) xpmem/2.2.15-6.0.7.1_5.11__g7549d06.ari
 13) job/2.2.3-6.0.7.1_5.43__g6c4e934.ari
 14) dvs/2.7_2.2.118-6.0.7.1_10.1__g58b37a2
 15) alps/6.6.43-6.0.7.1_5.45__ga796da32.ari
 16) rca/2.2.18-6.0.7.1_5.47__g2aa4f39.ari
 17) atp/2.1.3
 18) PrgEnv-intel/6.0.4
 19) craype-mic-knl
 20) cray-mpich/7.7.3
 21) gcc/7.3.0
 22) altd/2.0
 23) darshan/3.1.4
 24) cfitsio/3.370-reentrant
