### ISSUE TITLE
Loading libmadam causes an OpenMP error

### ISSUE THREAD

**Issue by ovlindho** [hpc4cmb/libmadam#2]
Running the script toast_satellite_sim.py with option --madam causes the following error:

`Traceback (most recent call last):
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/bin/toast_satellite_sim.py", line 4, in <module>
    __import__('pkg_resources').run_script('toast==2.0', 'toast_satellite_sim.py')
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/toast-2.0-py3.5-linux-x86_64.egg/EGG-INFO/scripts/toast_satellite_sim.py", line 357, in <module>
    main()
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/toast-2.0-py3.5-linux-x86_64.egg/EGG-INFO/scripts/toast_satellite_sim.py", line 345, in main
    madam.exec(data)
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/toast-2.0-py3.5-linux-x86_64.egg/toast/map/madam.py", line 146, in exec
    raise RuntimeError("Cannot find libmadam")
RuntimeError: Cannot find libmadam`

The actual error is hidden by the try-except statement in the file /homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/toast-2.0-py3.5-linux-x86_64.egg/toast/map/madam.py (lines 26-34). Adding the line libmadam = ct.CDLL('libmadam.so') before the try-except statement reveals the real error:

`Traceback (most recent call last):
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/bin/toast_satellite_sim.py", line 4, in <module>
    __import__('pkg_resources').run_script('toast==2.0', 'toast_satellite_sim.py')
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/toast-2.0-py3.5-linux-x86_64.egg/EGG-INFO/scripts/toast_satellite_sim.py", line 20, in <module>
    import toast.map as tm
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/toast-2.0-py3.5-linux-x86_64.egg/toast/map/__init__.py", line 8, in <module>
    from .madam import OpMadam
  File "/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/python3.5/site-packages/toast-2.0-py3.5-linux-x86_64.egg/toast/map/madam.py", line 25, in <module>
    libmadam = ct.CDLL('libmadam.so')
  File "/appl/opt/python/3.5.1-gnu520/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib/libmadam.so: undefined symbol: omp_get_num_threads_`

The system I'm compiling on is called "Sisu". The operating system is described as follows: 

"Sisu is a Linux cluster. The login nodes of Sisu are based on the SUSE Linux Enterprise Server 11.3 (SLES11.3) distribution. The computing nodes use a run-time environment provided by Cray, called Compute Node Linux (CNL).  Compute Node Linux, is a run-time environment based on SLES as well, but it includes only drivers, libraries and compilers required to run high-performance computing applications and a minimal amount of user-level commands (see http://www.busybox.net/)." 

The compiler I'm using is GNU Fortran (GCC) 5.3.0, apparently with some modifications by Cray. I'm compiling the code on the login nodes and running it on the computing nodes.

**Comment by tskisner** [comment]
The problem here is likely that libmadam.so does not contain the locations of its dependent libraries.  This is required for making stand-alone shared libraries that can be dlopened by ctypes on some systems.  @keskitalo , a solution might be to edit Makefile.am and add:

libmadam_la_LDFLAGS = -Wl,--no-undefined

One way to check if this works is to do "ldd libmadam.so".  The list of libraries should include things like cfitsio, fftw, and libgomp.

**Comment by ovlindho** [comment]
Before adding the line "libmadam_la_LDFLAGS = -Wl,--no-undefined", "ldd libmadam.so" gives the following list:

`linux-vdso.so.1 =>  (0x00002aaaaaaab000)
libfftw3.so.mpi31.3 => /opt/cray/fftw/3.3.4.7/sandybridge/lib/libfftw3.so.mpi31.3 (0x00002aaab4e34000)
libgfortran.so.3 => /opt/gcc/5.3.0/snos/lib64/libgfortran.so.3 (0x00002aaab5203000)
libm.so.6 => /lib64/libm.so.6 (0x00002aaab55a2000)
libfftw3f_mpi.so.mpi31.3 => /opt/cray/fftw/3.3.4.7/sandybridge/lib/libfftw3f_mpi.so.mpi31.3 (0x00002aaab581b000)
libfftw3f_threads.so.mpi31.3 => /opt/cray/fftw/3.3.4.7/sandybridge/lib/libfftw3f_threads.so.mpi31.3 (0x00002aaab5a31000)
libfftw3f.so.mpi31.3 => /opt/cray/fftw/3.3.4.7/sandybridge/lib/libfftw3f.so.mpi31.3 (0x00002aaab5c37000)
libfftw3_mpi.so.mpi31.3 => /opt/cray/fftw/3.3.4.7/sandybridge/lib/libfftw3_mpi.so.mpi31.3 (0x00002aaab6029000)
libfftw3_threads.so.mpi31.3 => /opt/cray/fftw/3.3.4.7/sandybridge/lib/libfftw3_threads.so.mpi31.3 (0x00002aaab623f000)
librca.so.0 => /opt/cray/rca/default/lib64/librca.so.0 (0x00002aaab6445000)
libsci_gnu_51.so.5 => /opt/cray/lib64/libsci_gnu_51.so.5 (0x00002aaab6649000)
libmpich_gnu_51.so.3 => /opt/cray/lib64/libmpich_gnu_51.so.3 (0x00002aaaba85c000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaabadeb000)
libgcc_s.so.1 => /opt/gcc/5.3.0/snos/lib64/libgcc_s.so.1 (0x00002aaabb008000)
libquadmath.so.0 => /opt/gcc/5.3.0/snos/lib64/libquadmath.so.0 (0x00002aaabb220000)
libc.so.6 => /lib64/libc.so.6 (0x00002aaabb45f000)
libmpich_gnu_49.so.3 => /opt/cray/lib64/libmpich_gnu_49.so.3 (0x00002aaabb7dc000)
libxpmem.so.0 => /opt/cray/xpmem/default/lib64/libxpmem.so.0 (0x00002aaabbd6b000)
librt.so.1 => /lib64/librt.so.1 (0x00002aaabbf6f000)
libugni.so.0 => /opt/cray/ugni/default/lib64/libugni.so.0 (0x00002aaabc178000)
libudreg.so.0 => /opt/cray/udreg/default/lib64/libudreg.so.0 (0x00002aaabc3eb000)
libpmi.so.0 => /opt/cray/pmi/default/lib64/libpmi.so.0 (0x00002aaabc5f5000)
libstdc++.so.6 => /opt/gcc/5.3.0/snos/lib64/libstdc++.so.6 (0x00002aaabc831000)
/lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
libdl.so.2 => /lib64/libdl.so.2 (0x00002aaabcbb5000)`

So it seems that indeed some of the dependent libraries are missing. After adding the line and running autogen.sh, configure (I have use --with-cfitsio= and --with-fftw= flags), make and make install the list is still the same.

**Comment by keskitalo** [comment]
All shared libraries are required at compile time as of 26710f4eab76051ddfbb9be9933084a960967976

Even without it, ldd src/.libs/libmadam.so showed that it included libgomp on NERSC Edison, so the OpenMP dependency was correctly being included. 

Can you post here what the linking command line looks like in your system. On Edison I'm seeing:

`libtool: link: ftn -shared  -fPIC  .libs/coordinate_conversion.o .libs/mpi_wrappers.o .libs/timing.o .libs/matrix.o .libs/fourier_fftw_2003.o .libs/planck_config.o .libs/planck_types.o .libs/ls_misc_utils.o .libs/linebufmod.o .libs/fitsmod2.o .libs/healpix_routines.o .libs/satellite.o .libs/simulation.o .libs/commonparam.o .libs/inputparam.o .libs/map_routines.o .libs/submap_transfer.o .libs/tod_storage.o .libs/noise_routines.o .libs/parameter_control.o .libs/pointing.o .libs/maps_and_baselines.o .libs/memory_and_time.o .libs/maptod_transfer.o .libs/read_data.o .libs/output.o .libs/smadam_routines.o .libs/covmat_util.o .libs/covmat.o .libs/smadam.o   -Wl,-rpath -Wl,/global/common/edison/contrib/desi/edison/python-3.4_gcc-5.2_mkl-15/lib -Wl,-rpath -Wl,/global/common/edison/contrib/desi/edison/python-3.4_gcc-5.2_mkl-15/lib -L/global/common/edison/contrib/desi/edison/python-3.4_gcc-5.2_mkl-15/lib -lcfitsio /global/common/edison/contrib/desi/edison/python-3.4_gcc-5.2_mkl-15/lib/libfftw3.so -lm  -O3 -fopenmp -Wl,--no-undefined -fopenmp   -fopenmp -Wl,-soname -Wl,libmadam.so.0 -o .libs/libmadam.so.0.0.0
`

With the critical -openmp included not once but twice. If yours is missing the flag, then we should take a look at your config.log.

**Comment by ovlindho** [comment]
Here are the linking commands for ftn and cc (this is after adding  the line "libmadam_la_LDFLAGS = -Wl,--no-undefined" in the file Makefile.am):

`libtool: link: ftn -shared  .libs/coordinate_conversion.o .libs/mpi_wrappers.o .libs/timing.o .libs/matrix.o .libs/fourier_fftw_2003.o .libs/planck_config.o .libs/planck_types.o .libs/ls_misc_utils.o .libs/linebufmod.o .libs/fitsmod2.o .libs/healpix_routines.o .libs/satellite.o .libs/simulation.o .libs/commonparam.o .libs/inputparam.o .libs/map_routines.o .libs/submap_transfer.o .libs/tod_storage.o .libs/noise_routines.o .libs/parameter_control.o .libs/pointing.o .libs/maps_and_baselines.o .libs/memory_and_time.o .libs/maptod_transfer.o .libs/read_data.o .libs/output.o .libs/smadam_routines.o .libs/covmat_util.o .libs/covmat.o .libs/smadam.o   -Wl,-rpath -Wl,/opt/cray/fftw/3.3.4.7/sandybridge/lib -Wl,-rpath -Wl,/opt/cray/fftw/3.3.4.7/sandybridge/lib -L/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib -lcfitsio -L/opt/cray/fftw/3.3.4.7/sandybridge/lib /opt/cray/fftw/3.3.4.7/sandybridge/lib/libfftw3.so -lm    -Wl,-soname -Wl,libmadam.so.0 -o .libs/libmadam.so.0.0.0`

`libtool: link: cc -O3 -fopenmp -fopenmp -o .libs/test_libmadam test_libmadam.o  ./.libs/libmadam.so -L/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib -L/opt/cray/fftw/3.3.4.7/sandybridge/lib -lcfitsio /opt/cray/fftw/3.3.4.7/sandybridge/lib/libfftw3.so -lm -Wl,-rpath -Wl,/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib -Wl,-rpath -Wl,/opt/cray/fftw/3.3.4.7/sandybridge/lib`

**Comment by keskitalo** [comment]
The problem is obvious from the top line. There is no -fopenmp set when linking the shared library. The configure script appends the same OpenMP flags to both FCFLAGS and LDFLAGS so it is rather unexpected to have them only get applied during compilation.

Can you post here your command line calling configure and the final lines of the configure output that show the build configuration? I think we are close to solving this issue.

**Comment by ovlindho** [comment]
Here is the configure call:

`./configure --prefix=/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb --with-cfitsio=/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb --with-fftw=/opt/cray/fftw/3.3.4.7/sandybridge`

And here is the build configuration:

`configure: =========== Build Configuration ===========
configure:                                            
configure:   Fortran Compiler          : ftn
configure:   Fortran Compile Flags     : -O3 -fopenmp
configure:   Fortran Linking Flags     :  -fopenmp
configure:   C Compiler                : cc
configure:   C Compile Flags           : -O3 -fopenmp
configure:   BLAS Link                 : 
configure:   LAPACK Link               : 
configure:   FFTW_CPPFLAGS             : -I/opt/cray/fftw/3.3.4.7/sandybridge/include -I/opt/cray/fftw/3.3.4.7/sandybridge/include
configure:   FFTW                      : -L/opt/cray/fftw/3.3.4.7/sandybridge/lib -lfftw3
configure:   CFITSIO Compile           : -I/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/include
configure:   CFITSIO Link              : -L/homeappl/home/ovlindho/appl_sisu/Virtualenvs/hpc4cmb/lib -lcfitsio
`

**Comment by keskitalo** [comment]
I'm closing this stale issue. Feel free to raise it again if compilation problems persist.
