### ISSUE TITLE
"make check" fails on Linux Mint 17.2

### ISSUE THREAD

**Issue by ziotom78** [hpc4cmb/libmadam#4]
After a successful configuration & build of `libmadam`, `make check` fails with the following error:

```
(snip)
FAIL: test_libmadam
FAIL: test_libmadam.py
(snip)
```

The first test (`test_libmadam`) fails with the following error:

```
(snip)
 Iteration done
    16 iteration steps

 Finalization begins

 Clock =     0.566 s
 Writing pixel matrix...
 FITSIO Error Status =         105 : couldn't create the named file
 failed to create new file (already exists?):                                    
 ./maps/madam_wcov_inv.fits                                                      
 FITS error
 program exits with exit code            1
```

I looked for a file named `madam_wcov_inv.fits`, but found no matches:

```
$ find ./ -name "madam*fits"
$
```

I have no idea why it fails here.

The second test (`test_libmadam.py`) fails with the following error message:

```
('Failed to load libmadam at ', '../../src/.libs/libmadam.so')
Traceback (most recent call last):
  File "../../src/test_libmadam.py", line 14, in <module>
    _madam = ctypes.CDLL( path.replace('.so','.dylib') )
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ../../src/.libs/libmadam.dylib: cannot open shared object file: No such file or directory
```

Here the problem is clearer, the test script assumes an OS X architecture (where dynamic libraries have extension `.dylib`). I would have happily submitted a PR, but I am not sure how to fix this (perhaps by a call to [find_library](https://docs.python.org/3/library/ctypes.html#finding-shared-libraries)?).

**Comment by keskitalo** [comment]
The first issue is simple and caused by a missing output directory. I'll fix that in a moment.

The other error message is misleading, as the test first tries to load the library using .so suffix and only then with the .dylib suffix. I'll add more verbosity to the part of the test where the shared library is located so that we can figure out if libtool has placed the shared library in some funny location. Clearly we need a Linux Mint  box for testing!

**Comment by keskitalo** [comment]
I have added code to ensure the output map directory is created before the tests are run. The shared library is now searched from both os.path.dirname( **file** )+'./libs' and './.libs/' and the progress of the progress is logged.

Maurizio, could you give the make check another go on your system?

**Comment by ziotom78** [comment]
Here is the output:

```
Traceback (most recent call last):
  File "../../src/test_libmadam.py", line 26, in <module>
    print(' FAILED', flush=True)
TypeError: 'flush' is an invalid keyword argument for this function
```

This made me realize why this is happening: the first line in `test_libmadam.py` contains the shebang

```
#!/usr/bin/env python
```

But under Linux Mint 17.2 `python` points to the `python2.7`, while `python3` points to `python3.4`:

```
$ ls -l $(which python) $(which python3)
lrwxrwxrwx 1 root root 9 Nov  3  2015 /usr/bin/python -> python2.7*
lrwxrwxrwx 1 root root 9 Nov  3  2015 /usr/bin/python3 -> python3.4*
```

So `make check` fails because it tries to run the test using Python 2 instead of Python 3. Manually running the command

```
python3 test_libmadam.py
```

makes the test complete with success.

Not sure how to fix this, the best option would be to make `configure` automatically detect the executable for the best Python interpreter and fire `test_libmadam.py` through an explicit call to this interpreter.

**Comment by keskitalo** [comment]
Apparently importing the Python3 print function from **future** does not include the flush keyword. I have replaced it with an explicit call to sys.stdout.flush() in 38c2b6c1db2ef85aff3d1dd962e364fe4a370c6b
