### ISSUE TITLE
Unable to use `-j N` flag with GMake

### ISSUE THREAD

**Issue by ziotom78** [hpc4cmb/libmadam#5]
Compiling the code with `make -j N` in order to spread the compilation over `N` jobs makes compilation fail:

```
(snip)
/bin/bash ../libtool  --tag=FC   --mode=compile mpif90  -I/usr/include -I/usr/include -O3 -fopenmp -c -o simulation.lo  ../../src/simulation.f90
../../src/satellite.f90:14.7:

   use healpix_routines
       1
Fatal Error: Can't open module file 'healpix_routines.mod' for reading at (1): No such file or directory
```

Avoiding `-j N` (or using `-j 1`) makes the code compile perfectly.

For me there is no need to try to fix this issue: I am just reporting this so that others who get struck with this are able to figure out what's happening. (I'm thinking of those who have a line like `export MAKEFLAGS=j4` buried in their `.bashrc`.)

**Comment by keskitalo** [comment]
This was a very useful observation. The automated dependency finding does not seem to work with Fortran. I have listed the explicit dependencies in Makefile.am in d6280dd085613dd6859a3d3537fa60b4a6bde9c1
